### ISSUE TITLE
Top block issue

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-Oksana-Shuliak#2]
This block
![image](https://cloud.githubusercontent.com/assets/25591824/23180639/bbfe0666-f87a-11e6-8fa2-54b8a933f9b6.png)

Must have bigger font with white color.
Also size of star and lines around it also have to be bigger.
![image](https://cloud.githubusercontent.com/assets/25591824/23180687/dfa28d12-f87a-11e6-8617-e18cfd33ed97.png)

**Comment by Oksana-Shuliak** [comment]
![image](https://cloud.githubusercontent.com/assets/25491466/23437460/e88ae1f8-fe16-11e6-9fc8-2f49727b31e9.png)
Can't make the lines around the star bigger.

**Comment by eko24ive** [comment]
I was able to do it, only by chaning value of css rules you declared for `.header .parent:before` :
![image](https://cloud.githubusercontent.com/assets/25591824/23503980/6b6ee422-ff46-11e6-8024-12236805e339.png)

Are you sure that you've completely stuck with this one ?

**Comment by Oksana-Shuliak** [comment]
Yep, it was really very simple. Thanks

**Comment by eko24ive** [comment]
You almost got it, now all is left is to put the lines a little bit lower:
![image](https://cloud.githubusercontent.com/assets/25591824/23542274/d9a4415e-fff4-11e6-8c8d-47c8e7c322e5.png)

So they will look like this:
![image](https://cloud.githubusercontent.com/assets/25591824/23542294/f4694dea-fff4-11e6-89e7-f6cb0f8710f1.png)

Agree ?

**Comment by Oksana-Shuliak** [comment]
Done

**Comment by eko24ive** [comment]
Sorry @Oksana-Shuliak I don't see any changes.
Also I can't find any commits where you fix it: https://github.com/Artinov/home-work-7-Oksana-Shuliak/commits/master
Haven't you forgot to push your commit ?

**Comment by Oksana-Shuliak** [comment]
Now the promlem should be solved)

**Comment by eko24ive** [comment]
Now this what I call perfection !
All your effort is perfect, don't slow it down !
